# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_children_cpp <- function(tree_mat, parent) {
    .Call(`_SoftHSMOTRBART_get_children_cpp`, tree_mat, parent)
}

phi_app_soft <- function(X_stand, anc, tau) {
    .Call(`_SoftHSMOTRBART_phi_app_soft`, X_stand, anc, tau)
}

phi_app_softHS <- function(treemat, internalmat, xmat, probmat) {
    .Call(`_SoftHSMOTRBART_phi_app_softHS`, treemat, internalmat, xmat, probmat)
}

